version: "3"
services:
  radarr:
    restart: always
    env_file: media.env
    image: linuxserver/radarr
    ports: ["7878:7878"]
    extra_hosts:
      - "host:${HOST_IP}"
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/radarr:/config"
      - "${MEDIA_DIR}/Movies:/movies"
  jackett: 
    restart: always
    env_file: media.env
    image: linuxserver/jackett
    ports: ["9117:9117"]
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/jackett:/config"
  nzbget: 
    restart: always
    env_file: media.env
    image: linuxserver/nzbget
    ports: ["6789:6789"]
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/nzbget:/config"
  plex: 
    restart: always
    env_file: plex.env
    environment: 
      - PLEX_CLAIM="${PLEX_CLAIM}"
    image: plexinc/pms-docker:plexpass
    network_mode: host
    volumes: 
      - "${CONFIG_DIR}/plex:/config"
      - "${MEDIA_DIR}:/data"
      - "${PLEX_TRANSCODE_DIR}:/transcode"
  ombi: 
    restart: always
    env_file: media.env
    image: linuxserver/ombi
    ports: ["3579:3579"]
    extra_hosts:
      - "host:${HOST_IP}"
    volumes: 
      - "${CONFIG_DIR}/ombi:/config"
      - "${MEDIA_DIR}/TV:/tv"
      - "${MEDIA_DIR}/Movies:/movies"
      - "/etc/localtime:/etc/locatime:ro"
  sonarr: 
    restart: always
    env_file: media.env
    image: linuxserver/sonarr
    ports: ["8989:8989"]
    extra_hosts:
      - "host:${HOST_IP}"
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/sonarr:/config"
      - "${MEDIA_DIR}/TV:/tv"
      - "/dev/rtc:/dev/rtc:ro"
  transmission: 
    restart: always
    env_file: media.env
    image: linuxserver/transmission
    ports: 
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/transmission:/config"
  tarsnapper:
    restart: always
    image: dangmai/tarsnapper
    volumes:
      - "${CONFIG_DIR}:/backup:ro"
      - "./tarsnapper.conf:/etc/tarsnapper.conf:ro"
      - "/root/tarsnap.key:/tarsnap/key:ro"
      - "/etc/localtime:/etc/localtime:ro"
  caddy:
    restart_policy:
      condition: any
      max_attempts: 3
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host:${HOST_IP}"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./basicauth.conf:/etc/basicauth.conf"
      - "${CONFIG_DIR}/caddy:/root/.caddy"
  portainer:
    restart: always
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

