version: "3"
services: 
  couchpotato: 
    env_file: media.env
    image: linuxserver/couchpotato
    network_mode: host
    ports: ["5050:5050"]
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/couchpotato:/config"
      - "${MEDIA_DIR}/Movies:/movies"
  jackett: 
    env_file: media.env
    image: linuxserver/jackett
    network_mode: host
    ports: ["9117:9117"]
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/jackett:/config"
  nzbget: 
    env_file: media.env
    image: linuxserver/nzbget
    network_mode: host
    ports: ["6789:6789"]
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/nzbget:/config"
  plex: 
    env_file: plex_media.env
    environment: 
      - PLEX_CLAIM="${PLEX_CLAIM}"
    image: plexinc/pms-docker
    network_mode: host
    volumes: 
      - "${CONFIG_DIR}/plex:/config"
      - "${MEDIA_DIR}:/data"
      - "${PLEX_TRANSCODE_DIR}:/transcode"
  ombi: 
    env_file: media.env
    image: linuxserver/ombi
    network_mode: host
    ports: ["3579:3579"]
    volumes: 
      - "${CONFIG_DIR}/ombi:/config"
      - "${MEDIA_DIR}/TV:/tv"
      - "/etc/localtime:/etc/locatime:ro"
  sonarr: 
    env_file: media.env
    image: linuxserver/sonarr
    network_mode: host
    ports: ["8989:8989"]
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/sonarr:/config"
      - "${MEDIA_DIR}/TV:/tv"
      - "/dev/rtc:/dev/rtc:ro"
  transmission: 
    env_file: media.env
    image: linuxserver/transmission
    network_mode: host
    ports: 
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/transmission:/config"

