version: "3"
services:
  radarr:
    restart: always
    env_file: media.env
    image: linuxserver/radarr
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/radarr:/config"
      - "${MEDIA_DIR}/Movies:/movies"
  jackett: 
    restart: always
    env_file: media.env
    image: linuxserver/jackett
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/jackett:/config"
  nzbget: 
    restart: always
    env_file: media.env
    image: linuxserver/nzbget
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/nzbget:/config"
  plex: 
    restart: always
    env_file: plex.env
    environment: 
      - PLEX_CLAIM="${PLEX_CLAIM}"
    image: plexinc/pms-docker:plexpass
    network_mode: host
    volumes: 
      - "${CONFIG_DIR}/plex:/config"
      - "${MEDIA_DIR}:/data"
      - "${PLEX_TRANSCODE_DIR}:/transcode"
  ombi: 
    restart: always
    env_file: media.env
    image: lsiodev/ombi-preview
    volumes: 
      - "${CONFIG_DIR}/ombi:/config"
      - "${MEDIA_DIR}/TV:/tv"
      - "${MEDIA_DIR}/Movies:/movies"
      - "/etc/localtime:/etc/locatime:ro"
  sonarr: 
    restart: always
    env_file: media.env
    image: linuxserver/sonarr
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/sonarr:/config"
      - "${MEDIA_DIR}/TV:/tv"
      - "/dev/rtc:/dev/rtc:ro"
  transmission: 
    restart: always
    env_file: media.env
    image: linuxserver/transmission
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    volumes: 
      - "${DOWNLOAD_DIR}:/downloads"
      - "${CONFIG_DIR}/transmission:/config"
  ddclient:
      restart: always
      image: linuxserver/ddclient
      volumes:
          - ${CONFIG_DIR}/ddclient:/config
  caddy:
    restart: on-failure:3
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${CONFIG_DIR}/caddy/Caddyfile:/etc/Caddyfile"
      - "${CONFIG_DIR}/caddy/basicauth.conf:/etc/basicauth.conf"
      - "${CONFIG_DIR}/caddy/storage:/root/.caddy"
